# Generated by Django 3.2.16 on 2024-08-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at'], 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
