# Generated by Django 3.2.16 on 2024-08-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comments_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='comment_text',
        ),
    ]
